sudo: required
services:
  - docker

before_install:
  - docker build -t benyoo5222jae/fib-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true benyoo5222jae/fib-client npm run test

after_sucess:
  - docker build -t benyoo5222jae/multi-fib-client ./client
  - docker build -t benyoo5222jae/mutli-fib-router ./nginx
  - docker build -t benyoo5222jae/multi-fib-server ./server
  - docker build -t benyoo5222jae/mutli-fib-worker ./worker
  # Now we need to push the newly built images to docker hub
  # To do so, we need to login to docker hub using "docker login" command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push benyoo5222jae/multi-fib-client
  - docker push benyoo5222jae/mutli-fib-router
  - docker push benyoo5222jae/multi-fib-server
  - docker push benyoo5222jae/mutli-fib-worker

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "Multi-container"
  end: "Multicontainer-env"
  bucket_name: "elasticbeanstalk-ca-central-1-423958764716"
  bucker_path: "Multi-container"
  on:
    branch: main
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_KEY
