version: "3"
services:
  redis-server:
    image: redis

  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password

  web-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./worker:/app"
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    environment:
      - WDS_SOCKET_PORT=0

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - web-server
      - client
