apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: k8sbenyoo-com-tls
spec:
  secretName: k8sbenyoo-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8sbenyoo.com
  dnsNames:
    - k8sbenyoo.com
    - www.k8sbenyoo.com
